//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectClassLibrary
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Question", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private ProjectClassLibrary.Chapter ChapterField;

        private System.Guid ChapterIdField;

        private System.Nullable<bool> DuplicateField;

        private string JustificationField;

        private System.Guid QuestionIdField;

        private string RequirementField;

        private ProjectClassLibrary.Response[] ResponsesField;

        private ProjectClassLibrary.TestQuestion[] TestQuestionsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Chapter Chapter
        {
            get
            {
                return this.ChapterField;
            }
            set
            {
                this.ChapterField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ChapterId
        {
            get
            {
                return this.ChapterIdField;
            }
            set
            {
                this.ChapterIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Duplicate
        {
            get
            {
                return this.DuplicateField;
            }
            set
            {
                this.DuplicateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Justification
        {
            get
            {
                return this.JustificationField;
            }
            set
            {
                this.JustificationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid QuestionId
        {
            get
            {
                return this.QuestionIdField;
            }
            set
            {
                this.QuestionIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Requirement
        {
            get
            {
                return this.RequirementField;
            }
            set
            {
                this.RequirementField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Response[] Responses
        {
            get
            {
                return this.ResponsesField;
            }
            set
            {
                this.ResponsesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.TestQuestion[] TestQuestions
        {
            get
            {
                return this.TestQuestionsField;
            }
            set
            {
                this.TestQuestionsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Chapter", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class Chapter : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid ChapterIdField;

        private ProjectClassLibrary.Question[] QuestionsField;

        private ProjectClassLibrary.Subject SubjectField;

        private System.Guid SubjectIdField;

        private ProjectClassLibrary.Test[] TestsField;

        private string TitleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ChapterId
        {
            get
            {
                return this.ChapterIdField;
            }
            set
            {
                this.ChapterIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Question[] Questions
        {
            get
            {
                return this.QuestionsField;
            }
            set
            {
                this.QuestionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Subject Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SubjectId
        {
            get
            {
                return this.SubjectIdField;
            }
            set
            {
                this.SubjectIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Test[] Tests
        {
            get
            {
                return this.TestsField;
            }
            set
            {
                this.TestsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Response", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string AnswerField;

        private bool CorrectField;

        private System.Nullable<bool> DuplicateField;

        private ProjectClassLibrary.Question QuestionField;

        private System.Guid QuestionIdField;

        private System.Guid ResponseIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer
        {
            get
            {
                return this.AnswerField;
            }
            set
            {
                this.AnswerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct
        {
            get
            {
                return this.CorrectField;
            }
            set
            {
                this.CorrectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Duplicate
        {
            get
            {
                return this.DuplicateField;
            }
            set
            {
                this.DuplicateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Question Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid QuestionId
        {
            get
            {
                return this.QuestionIdField;
            }
            set
            {
                this.QuestionIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ResponseId
        {
            get
            {
                return this.ResponseIdField;
            }
            set
            {
                this.ResponseIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "TestQuestion", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class TestQuestion : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<bool> DuplicateField;

        private int PunctajField;

        private ProjectClassLibrary.Question QuestionField;

        private System.Guid QuestionIdField;

        private ProjectClassLibrary.Test TestField;

        private System.Guid TestIdField;

        private ProjectClassLibrary.TestQuestion[] TestQuestion1Field;

        private ProjectClassLibrary.TestQuestion TestQuestion2Field;

        private System.Guid TestQuestionIdField;

        private System.Nullable<System.Guid> TestQuestionReferencedIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Duplicate
        {
            get
            {
                return this.DuplicateField;
            }
            set
            {
                this.DuplicateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Punctaj
        {
            get
            {
                return this.PunctajField;
            }
            set
            {
                this.PunctajField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Question Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid QuestionId
        {
            get
            {
                return this.QuestionIdField;
            }
            set
            {
                this.QuestionIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Test Test
        {
            get
            {
                return this.TestField;
            }
            set
            {
                this.TestField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TestId
        {
            get
            {
                return this.TestIdField;
            }
            set
            {
                this.TestIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.TestQuestion[] TestQuestion1
        {
            get
            {
                return this.TestQuestion1Field;
            }
            set
            {
                this.TestQuestion1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.TestQuestion TestQuestion2
        {
            get
            {
                return this.TestQuestion2Field;
            }
            set
            {
                this.TestQuestion2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TestQuestionId
        {
            get
            {
                return this.TestQuestionIdField;
            }
            set
            {
                this.TestQuestionIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> TestQuestionReferencedId
        {
            get
            {
                return this.TestQuestionReferencedIdField;
            }
            set
            {
                this.TestQuestionReferencedIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Subject", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private ProjectClassLibrary.Chapter[] ChaptersField;

        private string DescriptionField;

        private ProjectClassLibrary.Student[] StudentsField;

        private System.Guid SubjectIdField;

        private string TitleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Chapter[] Chapters
        {
            get
            {
                return this.ChaptersField;
            }
            set
            {
                this.ChaptersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Student[] Students
        {
            get
            {
                return this.StudentsField;
            }
            set
            {
                this.StudentsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SubjectId
        {
            get
            {
                return this.SubjectIdField;
            }
            set
            {
                this.SubjectIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Test", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class Test : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private ProjectClassLibrary.Chapter[] ChaptersField;

        private string DescriptionField;

        private System.Nullable<bool> DuplicateField;

        private ProjectClassLibrary.Examination[] ExaminationsField;

        private int NoQuestionsField;

        private int PunctajField;

        private ProjectClassLibrary.SolvedTest[] SolvedTestsField;

        private ProjectClassLibrary.Test[] Test1Field;

        private ProjectClassLibrary.Test Test2Field;

        private System.Guid TestIdField;

        private ProjectClassLibrary.TestQuestion[] TestQuestionsField;

        private System.Nullable<System.Guid> TestReferencedIdField;

        private int TimeToSolveField;

        private string TitleField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Chapter[] Chapters
        {
            get
            {
                return this.ChaptersField;
            }
            set
            {
                this.ChaptersField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Duplicate
        {
            get
            {
                return this.DuplicateField;
            }
            set
            {
                this.DuplicateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Examination[] Examinations
        {
            get
            {
                return this.ExaminationsField;
            }
            set
            {
                this.ExaminationsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoQuestions
        {
            get
            {
                return this.NoQuestionsField;
            }
            set
            {
                this.NoQuestionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Punctaj
        {
            get
            {
                return this.PunctajField;
            }
            set
            {
                this.PunctajField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.SolvedTest[] SolvedTests
        {
            get
            {
                return this.SolvedTestsField;
            }
            set
            {
                this.SolvedTestsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Test[] Test1
        {
            get
            {
                return this.Test1Field;
            }
            set
            {
                this.Test1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Test Test2
        {
            get
            {
                return this.Test2Field;
            }
            set
            {
                this.Test2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TestId
        {
            get
            {
                return this.TestIdField;
            }
            set
            {
                this.TestIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.TestQuestion[] TestQuestions
        {
            get
            {
                return this.TestQuestionsField;
            }
            set
            {
                this.TestQuestionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> TestReferencedId
        {
            get
            {
                return this.TestReferencedIdField;
            }
            set
            {
                this.TestReferencedIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeToSolve
        {
            get
            {
                return this.TimeToSolveField;
            }
            set
            {
                this.TimeToSolveField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Student", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private ProjectClassLibrary.Examination[] ExaminationsField;

        private string FirstNameField;

        private string LastNameField;

        private ProjectClassLibrary.SolvedTest[] SolvedTestsField;

        private System.Guid StudentIdField;

        private ProjectClassLibrary.Subject[] SubjectsField;

        private ProjectClassLibrary.User[] UsersField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Examination[] Examinations
        {
            get
            {
                return this.ExaminationsField;
            }
            set
            {
                this.ExaminationsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.SolvedTest[] SolvedTests
        {
            get
            {
                return this.SolvedTestsField;
            }
            set
            {
                this.SolvedTestsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Subject[] Subjects
        {
            get
            {
                return this.SubjectsField;
            }
            set
            {
                this.SubjectsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.User[] Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Examination", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class Examination : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime DateField;

        private string DescriptionField;

        private System.Guid ExaminationIdField;

        private ProjectClassLibrary.Student[] StudentsField;

        private ProjectClassLibrary.Test TestField;

        private System.Guid TestIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ExaminationId
        {
            get
            {
                return this.ExaminationIdField;
            }
            set
            {
                this.ExaminationIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Student[] Students
        {
            get
            {
                return this.StudentsField;
            }
            set
            {
                this.StudentsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Test Test
        {
            get
            {
                return this.TestField;
            }
            set
            {
                this.TestField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TestId
        {
            get
            {
                return this.TestIdField;
            }
            set
            {
                this.TestIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SolvedTest", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class SolvedTest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<bool> PendingField;

        private int PunctajField;

        private System.Guid SolvedTestIdField;

        private ProjectClassLibrary.Student StudentField;

        private System.Guid StudentIdField;

        private ProjectClassLibrary.Test TestField;

        private System.Guid TestIdField;

        private System.TimeSpan TimeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Pending
        {
            get
            {
                return this.PendingField;
            }
            set
            {
                this.PendingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Punctaj
        {
            get
            {
                return this.PunctajField;
            }
            set
            {
                this.PunctajField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SolvedTestId
        {
            get
            {
                return this.SolvedTestIdField;
            }
            set
            {
                this.SolvedTestIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Student Student
        {
            get
            {
                return this.StudentField;
            }
            set
            {
                this.StudentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Test Test
        {
            get
            {
                return this.TestField;
            }
            set
            {
                this.TestField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TestId
        {
            get
            {
                return this.TestIdField;
            }
            set
            {
                this.TestIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "User", Namespace = "http://schemas.datacontract.org/2004/07/ProjectClassLibrary", IsReference = true)]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string EmailField;

        private string PasswordField;

        private ProjectClassLibrary.Student StudentField;

        private System.Guid StudentIdField;

        private System.Guid UserIdField;

        private int UserTypeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProjectClassLibrary.Student Student
        {
            get
            {
                return this.StudentField;
            }
            set
            {
                this.StudentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid StudentId
        {
            get
            {
                return this.StudentIdField;
            }
            set
            {
                this.StudentIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserType
        {
            get
            {
                return this.UserTypeField;
            }
            set
            {
                this.UserTypeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IServerLector")]
public interface IServerLector
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddSubject")]
    void TestAddSubject();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddSubject")]
    System.Threading.Tasks.Task TestAddSubjectAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintSubjects")]
    void PrintSubjects();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintSubjects")]
    System.Threading.Tasks.Task PrintSubjectsAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddChapter")]
    void TestAddChapter();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddChapter")]
    System.Threading.Tasks.Task TestAddChapterAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintChapters")]
    void PrintChapters();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintChapters")]
    System.Threading.Tasks.Task PrintChaptersAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddStudentUser")]
    void TestAddStudentUser();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddStudentUser")]
    System.Threading.Tasks.Task TestAddStudentUserAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintStudents")]
    void PrintStudents();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintStudents")]
    System.Threading.Tasks.Task PrintStudentsAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddQuestion")]
    void TestAddQuestion();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddQuestion")]
    System.Threading.Tasks.Task TestAddQuestionAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintQuestions")]
    void PrintQuestions();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintQuestions")]
    System.Threading.Tasks.Task PrintQuestionsAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddTest")]
    void TestAddTest();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddTest")]
    System.Threading.Tasks.Task TestAddTestAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintTests")]
    void PrintTests();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintTests")]
    System.Threading.Tasks.Task PrintTestsAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddExamination")]
    void TestAddExamination();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddExamination")]
    System.Threading.Tasks.Task TestAddExaminationAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintExaminations")]
    void PrintExaminations();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintExaminations")]
    System.Threading.Tasks.Task PrintExaminationsAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddSolvedTest")]
    void TestAddSolvedTest();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/TestAddSolvedTest")]
    System.Threading.Tasks.Task TestAddSolvedTestAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintSolvedTests")]
    void PrintSolvedTests();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/PrintSolvedTests")]
    System.Threading.Tasks.Task PrintSolvedTestsAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/DeleteAll")]
    void DeleteAll();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/DeleteAll")]
    System.Threading.Tasks.Task DeleteAllAsync();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/ModifyRemoveCreateQuestion")]
    void ModifyRemoveCreateQuestion(ProjectClassLibrary.Question question);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/ModifyRemoveCreateQuestion")]
    System.Threading.Tasks.Task ModifyRemoveCreateQuestionAsync(ProjectClassLibrary.Question question);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/ModifyRemoveCreateTest")]
    void ModifyRemoveCreateTest(ProjectClassLibrary.Test test);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/ModifyRemoveCreateTest")]
    System.Threading.Tasks.Task ModifyRemoveCreateTestAsync(ProjectClassLibrary.Test test);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/AddOpp", ReplyAction = "http://tempuri.org/IServerLector/AddOppResponse")]
    int AddOpp(int a, int b);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/AddOpp", ReplyAction = "http://tempuri.org/IServerLector/AddOppResponse")]
    System.Threading.Tasks.Task<int> AddOppAsync(int a, int b);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/AddAll")]
    void AddAll();

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IServerLector/AddAll")]
    System.Threading.Tasks.Task AddAllAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSubjects", ReplyAction = "http://tempuri.org/IServerLector/GetSubjectsResponse")]
    ProjectClassLibrary.Subject[] GetSubjects(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSubjects", ReplyAction = "http://tempuri.org/IServerLector/GetSubjectsResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Subject[]> GetSubjectsAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetChapters", ReplyAction = "http://tempuri.org/IServerLector/GetChaptersResponse")]
    ProjectClassLibrary.Chapter[] GetChapters(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetChapters", ReplyAction = "http://tempuri.org/IServerLector/GetChaptersResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Chapter[]> GetChaptersAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTests", ReplyAction = "http://tempuri.org/IServerLector/GetTestsResponse")]
    ProjectClassLibrary.Test[] GetTests(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTests", ReplyAction = "http://tempuri.org/IServerLector/GetTestsResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Test[]> GetTestsAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetStudents", ReplyAction = "http://tempuri.org/IServerLector/GetStudentsResponse")]
    ProjectClassLibrary.Student[] GetStudents(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetStudents", ReplyAction = "http://tempuri.org/IServerLector/GetStudentsResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Student[]> GetStudentsAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetQuestions", ReplyAction = "http://tempuri.org/IServerLector/GetQuestionsResponse")]
    ProjectClassLibrary.Question[] GetQuestions(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetQuestions", ReplyAction = "http://tempuri.org/IServerLector/GetQuestionsResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Question[]> GetQuestionsAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetExaminations", ReplyAction = "http://tempuri.org/IServerLector/GetExaminationsResponse")]
    ProjectClassLibrary.Examination[] GetExaminations(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetExaminations", ReplyAction = "http://tempuri.org/IServerLector/GetExaminationsResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Examination[]> GetExaminationsAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetUsers", ReplyAction = "http://tempuri.org/IServerLector/GetUsersResponse")]
    ProjectClassLibrary.User[] GetUsers(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetUsers", ReplyAction = "http://tempuri.org/IServerLector/GetUsersResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.User[]> GetUsersAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTestQuestions", ReplyAction = "http://tempuri.org/IServerLector/GetTestQuestionsResponse")]
    ProjectClassLibrary.TestQuestion[] GetTestQuestions(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTestQuestions", ReplyAction = "http://tempuri.org/IServerLector/GetTestQuestionsResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.TestQuestion[]> GetTestQuestionsAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSolvedTests", ReplyAction = "http://tempuri.org/IServerLector/GetSolvedTestsResponse")]
    ProjectClassLibrary.SolvedTest[] GetSolvedTests(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSolvedTests", ReplyAction = "http://tempuri.org/IServerLector/GetSolvedTestsResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.SolvedTest[]> GetSolvedTestsAsync(string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSubject", ReplyAction = "http://tempuri.org/IServerLector/GetSubjectResponse")]
    ProjectClassLibrary.Subject GetSubject(System.Guid subjectID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSubject", ReplyAction = "http://tempuri.org/IServerLector/GetSubjectResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Subject> GetSubjectAsync(System.Guid subjectID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetChapter", ReplyAction = "http://tempuri.org/IServerLector/GetChapterResponse")]
    ProjectClassLibrary.Chapter GetChapter(System.Guid chapterID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetChapter", ReplyAction = "http://tempuri.org/IServerLector/GetChapterResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Chapter> GetChapterAsync(System.Guid chapterID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTest", ReplyAction = "http://tempuri.org/IServerLector/GetTestResponse")]
    ProjectClassLibrary.Test GetTest(System.Guid testID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTest", ReplyAction = "http://tempuri.org/IServerLector/GetTestResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Test> GetTestAsync(System.Guid testID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetStudent", ReplyAction = "http://tempuri.org/IServerLector/GetStudentResponse")]
    ProjectClassLibrary.Student GetStudent(System.Guid studentID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetStudent", ReplyAction = "http://tempuri.org/IServerLector/GetStudentResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Student> GetStudentAsync(System.Guid studentID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetQuestion", ReplyAction = "http://tempuri.org/IServerLector/GetQuestionResponse")]
    ProjectClassLibrary.Question GetQuestion(System.Guid questionID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetQuestion", ReplyAction = "http://tempuri.org/IServerLector/GetQuestionResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Question> GetQuestionAsync(System.Guid questionID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetExamination", ReplyAction = "http://tempuri.org/IServerLector/GetExaminationResponse")]
    ProjectClassLibrary.Examination GetExamination(System.Guid examinationID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetExamination", ReplyAction = "http://tempuri.org/IServerLector/GetExaminationResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.Examination> GetExaminationAsync(System.Guid examinationID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetUser", ReplyAction = "http://tempuri.org/IServerLector/GetUserResponse")]
    ProjectClassLibrary.User GetUser(System.Guid userID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetUser", ReplyAction = "http://tempuri.org/IServerLector/GetUserResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.User> GetUserAsync(System.Guid userID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTestQuestion", ReplyAction = "http://tempuri.org/IServerLector/GetTestQuestionResponse")]
    ProjectClassLibrary.TestQuestion GetTestQuestion(System.Guid testQuestionID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetTestQuestion", ReplyAction = "http://tempuri.org/IServerLector/GetTestQuestionResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.TestQuestion> GetTestQuestionAsync(System.Guid testQuestionID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSolvedTest", ReplyAction = "http://tempuri.org/IServerLector/GetSolvedTestResponse")]
    ProjectClassLibrary.SolvedTest GetSolvedTest(System.Guid solvedTestID, string includeProperties = "");

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServerLector/GetSolvedTest", ReplyAction = "http://tempuri.org/IServerLector/GetSolvedTestResponse")]
    System.Threading.Tasks.Task<ProjectClassLibrary.SolvedTest> GetSolvedTestAsync(System.Guid solvedTestID, string includeProperties = "");
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerLectorChannel : IServerLector, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerLectorClient : System.ServiceModel.ClientBase<IServerLector>, IServerLector
{

    public ServerLectorClient()
    {
    }

    public ServerLectorClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public ServerLectorClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ServerLectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ServerLectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public void TestAddSubject()
    {
        base.Channel.TestAddSubject();
    }

    public System.Threading.Tasks.Task TestAddSubjectAsync()
    {
        return base.Channel.TestAddSubjectAsync();
    }

    public void PrintSubjects()
    {
        base.Channel.PrintSubjects();
    }

    public System.Threading.Tasks.Task PrintSubjectsAsync()
    {
        return base.Channel.PrintSubjectsAsync();
    }

    public void TestAddChapter()
    {
        base.Channel.TestAddChapter();
    }

    public System.Threading.Tasks.Task TestAddChapterAsync()
    {
        return base.Channel.TestAddChapterAsync();
    }

    public void PrintChapters()
    {
        base.Channel.PrintChapters();
    }

    public System.Threading.Tasks.Task PrintChaptersAsync()
    {
        return base.Channel.PrintChaptersAsync();
    }

    public void TestAddStudentUser()
    {
        base.Channel.TestAddStudentUser();
    }

    public System.Threading.Tasks.Task TestAddStudentUserAsync()
    {
        return base.Channel.TestAddStudentUserAsync();
    }

    public void PrintStudents()
    {
        base.Channel.PrintStudents();
    }

    public System.Threading.Tasks.Task PrintStudentsAsync()
    {
        return base.Channel.PrintStudentsAsync();
    }

    public void TestAddQuestion()
    {
        base.Channel.TestAddQuestion();
    }

    public System.Threading.Tasks.Task TestAddQuestionAsync()
    {
        return base.Channel.TestAddQuestionAsync();
    }

    public void PrintQuestions()
    {
        base.Channel.PrintQuestions();
    }

    public System.Threading.Tasks.Task PrintQuestionsAsync()
    {
        return base.Channel.PrintQuestionsAsync();
    }

    public void TestAddTest()
    {
        base.Channel.TestAddTest();
    }

    public System.Threading.Tasks.Task TestAddTestAsync()
    {
        return base.Channel.TestAddTestAsync();
    }

    public void PrintTests()
    {
        base.Channel.PrintTests();
    }

    public System.Threading.Tasks.Task PrintTestsAsync()
    {
        return base.Channel.PrintTestsAsync();
    }

    public void TestAddExamination()
    {
        base.Channel.TestAddExamination();
    }

    public System.Threading.Tasks.Task TestAddExaminationAsync()
    {
        return base.Channel.TestAddExaminationAsync();
    }

    public void PrintExaminations()
    {
        base.Channel.PrintExaminations();
    }

    public System.Threading.Tasks.Task PrintExaminationsAsync()
    {
        return base.Channel.PrintExaminationsAsync();
    }

    public void TestAddSolvedTest()
    {
        base.Channel.TestAddSolvedTest();
    }

    public System.Threading.Tasks.Task TestAddSolvedTestAsync()
    {
        return base.Channel.TestAddSolvedTestAsync();
    }

    public void PrintSolvedTests()
    {
        base.Channel.PrintSolvedTests();
    }

    public System.Threading.Tasks.Task PrintSolvedTestsAsync()
    {
        return base.Channel.PrintSolvedTestsAsync();
    }

    public void DeleteAll()
    {
        base.Channel.DeleteAll();
    }

    public System.Threading.Tasks.Task DeleteAllAsync()
    {
        return base.Channel.DeleteAllAsync();
    }

    public void ModifyRemoveCreateQuestion(ProjectClassLibrary.Question question)
    {
        base.Channel.ModifyRemoveCreateQuestion(question);
    }

    public System.Threading.Tasks.Task ModifyRemoveCreateQuestionAsync(ProjectClassLibrary.Question question)
    {
        return base.Channel.ModifyRemoveCreateQuestionAsync(question);
    }

    public void ModifyRemoveCreateTest(ProjectClassLibrary.Test test)
    {
        base.Channel.ModifyRemoveCreateTest(test);
    }

    public System.Threading.Tasks.Task ModifyRemoveCreateTestAsync(ProjectClassLibrary.Test test)
    {
        return base.Channel.ModifyRemoveCreateTestAsync(test);
    }

    public int AddOpp(int a, int b)
    {
        return base.Channel.AddOpp(a, b);
    }

    public System.Threading.Tasks.Task<int> AddOppAsync(int a, int b)
    {
        return base.Channel.AddOppAsync(a, b);
    }

    public void AddAll()
    {
        base.Channel.AddAll();
    }

    public System.Threading.Tasks.Task AddAllAsync()
    {
        return base.Channel.AddAllAsync();
    }

    public ProjectClassLibrary.Subject[] GetSubjects(string includeProperties = "")
    {
        return base.Channel.GetSubjects(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Subject[]> GetSubjectsAsync(string includeProperties = "")
    {
        return base.Channel.GetSubjectsAsync(includeProperties);
    }

    public ProjectClassLibrary.Chapter[] GetChapters(string includeProperties = "")
    {
        return base.Channel.GetChapters(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Chapter[]> GetChaptersAsync(string includeProperties = "")
    {
        return base.Channel.GetChaptersAsync(includeProperties);
    }

    public ProjectClassLibrary.Test[] GetTests(string includeProperties = "")
    {
        return base.Channel.GetTests(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Test[]> GetTestsAsync(string includeProperties = "")
    {
        return base.Channel.GetTestsAsync(includeProperties);
    }

    public ProjectClassLibrary.Student[] GetStudents(string includeProperties = "")
    {
        return base.Channel.GetStudents(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Student[]> GetStudentsAsync(string includeProperties = "")
    {
        return base.Channel.GetStudentsAsync(includeProperties);
    }

    public ProjectClassLibrary.Question[] GetQuestions(string includeProperties = "")
    {
        return base.Channel.GetQuestions(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Question[]> GetQuestionsAsync(string includeProperties = "")
    {
        return base.Channel.GetQuestionsAsync(includeProperties);
    }

    public ProjectClassLibrary.Examination[] GetExaminations(string includeProperties = "")
    {
        return base.Channel.GetExaminations(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Examination[]> GetExaminationsAsync(string includeProperties = "")
    {
        return base.Channel.GetExaminationsAsync(includeProperties);
    }

    public ProjectClassLibrary.User[] GetUsers(string includeProperties = "")
    {
        return base.Channel.GetUsers(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.User[]> GetUsersAsync(string includeProperties = "")
    {
        return base.Channel.GetUsersAsync(includeProperties);
    }

    public ProjectClassLibrary.TestQuestion[] GetTestQuestions(string includeProperties = "")
    {
        return base.Channel.GetTestQuestions(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.TestQuestion[]> GetTestQuestionsAsync(string includeProperties = "")
    {
        return base.Channel.GetTestQuestionsAsync(includeProperties);
    }

    public ProjectClassLibrary.SolvedTest[] GetSolvedTests(string includeProperties = "")
    {
        return base.Channel.GetSolvedTests(includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.SolvedTest[]> GetSolvedTestsAsync(string includeProperties = "")
    {
        return base.Channel.GetSolvedTestsAsync(includeProperties);
    }

    public ProjectClassLibrary.Subject GetSubject(System.Guid subjectID, string includeProperties = "")
    {
        return base.Channel.GetSubject(subjectID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Subject> GetSubjectAsync(System.Guid subjectID, string includeProperties = "")
    {
        return base.Channel.GetSubjectAsync(subjectID, includeProperties);
    }

    public ProjectClassLibrary.Chapter GetChapter(System.Guid chapterID, string includeProperties = "")
    {
        return base.Channel.GetChapter(chapterID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Chapter> GetChapterAsync(System.Guid chapterID, string includeProperties = "")
    {
        return base.Channel.GetChapterAsync(chapterID, includeProperties);
    }

    public ProjectClassLibrary.Test GetTest(System.Guid testID, string includeProperties = "")
    {
        return base.Channel.GetTest(testID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Test> GetTestAsync(System.Guid testID, string includeProperties = "")
    {
        return base.Channel.GetTestAsync(testID, includeProperties);
    }

    public ProjectClassLibrary.Student GetStudent(System.Guid studentID, string includeProperties = "")
    {
        return base.Channel.GetStudent(studentID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Student> GetStudentAsync(System.Guid studentID, string includeProperties = "")
    {
        return base.Channel.GetStudentAsync(studentID, includeProperties);
    }

    public ProjectClassLibrary.Question GetQuestion(System.Guid questionID, string includeProperties = "")
    {
        return base.Channel.GetQuestion(questionID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Question> GetQuestionAsync(System.Guid questionID, string includeProperties = "")
    {
        return base.Channel.GetQuestionAsync(questionID, includeProperties);
    }

    public ProjectClassLibrary.Examination GetExamination(System.Guid examinationID, string includeProperties = "")
    {
        return base.Channel.GetExamination(examinationID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.Examination> GetExaminationAsync(System.Guid examinationID, string includeProperties = "")
    {
        return base.Channel.GetExaminationAsync(examinationID, includeProperties);
    }

    public ProjectClassLibrary.User GetUser(System.Guid userID, string includeProperties = "")
    {
        return base.Channel.GetUser(userID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.User> GetUserAsync(System.Guid userID, string includeProperties = "")
    {
        return base.Channel.GetUserAsync(userID, includeProperties);
    }

    public ProjectClassLibrary.TestQuestion GetTestQuestion(System.Guid testQuestionID, string includeProperties = "")
    {
        return base.Channel.GetTestQuestion(testQuestionID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.TestQuestion> GetTestQuestionAsync(System.Guid testQuestionID, string includeProperties = "")
    {
        return base.Channel.GetTestQuestionAsync(testQuestionID, includeProperties);
    }

    public ProjectClassLibrary.SolvedTest GetSolvedTest(System.Guid solvedTestID, string includeProperties = "")
    {
        return base.Channel.GetSolvedTest(solvedTestID, includeProperties);
    }

    public System.Threading.Tasks.Task<ProjectClassLibrary.SolvedTest> GetSolvedTestAsync(System.Guid solvedTestID, string includeProperties = "")
    {
        return base.Channel.GetSolvedTestAsync(solvedTestID, includeProperties);
    }
}
